import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { classifySessionTermination } from "./session-termination.mjs";
import { acknowledgeCrossWorkerRecovery, planCrossWorkerRecovery } from "./cross-worker-recovery.mjs";
import { evaluateResumePreflight } from "./resume-preflight.mjs";

function checkpoint(overrides = {}) {
  const base = { checkpoint_version: 1, revision: 5, task: { id: "task-1", project: "project", goal: "goal", phase: "execute", status: "open" }, gates: { completed: ["intake"], open: ["execute"] }, workspace: { path: "/work", git_sha: "abc", branch: "main" }, constraints: { items: [], approval: { status: "not_required", request_refs: [] } }, evidence_refs: [{ id: "e1", kind: "test", locator: "evidence://1", digest: null }], receipt_refs: [{ id: "r1", kind: "receipt", locator: "receipt://1", digest: null }], handoff_refs: [{ id: "h1", kind: "handoff", locator: "handoff://1", digest: null }], semantic_progress: { semantic_state: "productive", last_productive_at: null, last_productive_cursor: 2, thinking_tokens_since_productive: 0 }, last_execution: { worker_id: "codex", native_session_id: "session-old", native_status: "failed" }, continuation: { next_action: { kind: "run_gate", gate_id: "execute", input_ref: null }, resume_cursor: "gate:execute", retry_count: 0, safe_to_resume: true } };
  return { ...base, ...overrides };
}
function workerState(overrides = {}) { return { workers: { codex: { availability: "available", budget_pressure: "normal" }, claude: { availability: "available", budget_pressure: "normal" }, pi: { availability: "available", budget_pressure: "normal" } }, ...overrides }; }
function termination(state = checkpoint()) { return classifySessionTermination({ checkpoint: state, termination_evidence: { signals: ["tool_runtime_failure"] } }); }
function plan(state = checkpoint(), overrides = {}) { return planCrossWorkerRecovery({ checkpoint: state, termination_result: termination(state), task: { task_class: "general_engineering" }, worker_state: workerState(), routing_policy: {}, policy: { max_reroute_count: 2 }, ...overrides }); }
function facts(effect = { kind: "none", status: "none", prior_claim_keys: [] }, human_block = "none") { return { workspace: { path: "/work", git_sha: "abc", branch: "main" }, human_block, effect }; }

test("eligible classifier result routes through existing policy to a different supported worker", () => { const value = plan(); assert.equal(value.planned, true); assert.equal(value.action, "spawn_cross_worker"); assert.equal(value.source_worker_id, "codex"); assert.equal(value.target_worker_id, "claude"); assert.notEqual(value.target_worker_id, value.source_worker_id); assert.equal(value.target_native_session_id, null); });
test("existing capability and availability policy controls the target", () => { const value = plan(checkpoint(), { task: { task_class: "general_engineering" }, worker_state: workerState({ workers: { codex: { availability: "available" }, claude: { availability: "unavailable" }, pi: { availability: "available" } } }) }); assert.equal(value.target_worker_id, "pi"); const none = plan(checkpoint(), { worker_state: workerState({ workers: { codex: { availability: "available" }, claude: { availability: "unavailable" }, pi: { availability: "unavailable" } } }) }); assert.equal(none.reason_code, "no_supported_target_worker"); });
test("terminal, unsafe, approval-blocked, ineligible, and exhausted tasks do not plan", () => { const terminal = checkpoint({ task: { ...checkpoint().task, status: "completed" } }); assert.equal(planCrossWorkerRecovery({ checkpoint: terminal, termination_result: termination(terminal), task: {}, worker_state: workerState(), policy: { max_reroute_count: 2 } }).planned, false); const unsafe = checkpoint({ continuation: { ...checkpoint().continuation, safe_to_resume: false } }); assert.equal(plan(unsafe).reason_code, "checkpoint_not_safe_to_resume"); const approval = checkpoint({ constraints: { items: [], approval: { status: "pending", request_refs: ["approval:1"] } } }); assert.equal(plan(approval).reason_code, "approval_blocks_reroute"); const exhausted = checkpoint({ continuation: { ...checkpoint().continuation, retry_count: 2 } }); assert.equal(plan(exhausted).reason_code, "reroute_budget_exhausted"); const wrong = classifySessionTermination({ checkpoint: checkpoint(), termination_evidence: { signals: ["unknown"] } }); assert.equal(planCrossWorkerRecovery({ checkpoint: checkpoint(), termination_result: wrong, task: {}, worker_state: workerState(), policy: { max_reroute_count: 2 } }).planned, false); });
test("plan is deterministic, bounded, immutable, and preserves checkpoint material", () => { const state = checkpoint(); const before = structuredClone(state); const first = plan(state); assert.deepEqual(plan(state), first); assert.deepEqual(state, before); assert.match(first.claim_key, /^sha256:[0-9a-f]{64}$/); for (const key of ["workspace", "gates", "constraints", "evidence_refs", "receipt_refs", "handoff_refs", "semantic_progress"]) assert.deepEqual(first[key], state[key], key); });
test("ASR-4 preflight permits clean cross-worker plan and blocks stale/human/effect ambiguity/duplicates", () => { const state = checkpoint(); const recovery = plan(state); assert.equal(evaluateResumePreflight({ checkpoint: state, plan: recovery, runtime_facts: facts() }).execution_allowed, true); assert.equal(evaluateResumePreflight({ checkpoint: { ...state, revision: 6 }, plan: recovery, runtime_facts: facts() }).decision, "stale_replan"); assert.equal(evaluateResumePreflight({ checkpoint: state, plan: recovery, runtime_facts: facts(undefined, "safety_block") }).decision, "human_required"); assert.equal(evaluateResumePreflight({ checkpoint: state, plan: recovery, runtime_facts: facts({ kind: "mutating", status: "unknown", prior_claim_keys: [] }) }).decision, "recovery_required"); assert.equal(evaluateResumePreflight({ checkpoint: state, plan: recovery, runtime_facts: facts({ kind: "mutating", status: "applied", prior_claim_keys: [] }) }).decision, "already_completed"); assert.equal(evaluateResumePreflight({ checkpoint: state, plan: recovery, runtime_facts: facts({ kind: "none", status: "none", prior_claim_keys: [recovery.claim_key] }) }).reason_code, "claim_already_recorded"); });
test("host acknowledgement installs target session, advances state, and preserves durable material", () => { const state = checkpoint(); const recovery = plan(state); const updated = acknowledgeCrossWorkerRecovery({ checkpoint: state, plan: recovery, new_native_session_id: "session-new" }); assert.equal(updated.revision, state.revision + 1); assert.equal(updated.continuation.retry_count, state.continuation.retry_count + 1); assert.deepEqual(updated.last_execution, { worker_id: recovery.target_worker_id, native_session_id: "session-new", native_status: "running" }); for (const key of ["task", "gates", "workspace", "constraints", "evidence_refs", "receipt_refs", "handoff_refs", "semantic_progress"]) assert.deepEqual(updated[key], state[key], key); assert.deepEqual(acknowledgeCrossWorkerRecovery({ checkpoint: updated, plan: recovery, new_native_session_id: "session-new" }), updated); });
test("ack rejects stale, mismatched, source-worker, unsupported-target, and reused-session transitions", () => { const state = checkpoint(); const recovery = plan(state); assert.throws(() => acknowledgeCrossWorkerRecovery({ checkpoint: { ...state, revision: 6 }, plan: recovery, new_native_session_id: "new" }), /revision/); assert.throws(() => acknowledgeCrossWorkerRecovery({ checkpoint: state, plan: { ...recovery, target_worker_id: recovery.source_worker_id }, new_native_session_id: "new" }), /must differ/); assert.throws(() => acknowledgeCrossWorkerRecovery({ checkpoint: state, plan: { ...recovery, target_worker_id: "unsupported" }, new_native_session_id: "new" }), /unsupported/); assert.throws(() => acknowledgeCrossWorkerRecovery({ checkpoint: state, plan: recovery, new_native_session_id: recovery.source_native_session_id }), /must differ/); });
test("external orchestrator is not referenced or required", () => { const source = readFileSync(new URL("./cross-worker-recovery.mjs", import.meta.url), "utf8"); assert.equal(source.includes(["Agent", "Navi"].join("")), false); });
