import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { classifySessionTermination } from "./session-termination.mjs";
import { planSameWorkerRespawn } from "./same-worker-respawn.mjs";
import { evaluateResumePreflight } from "./resume-preflight.mjs";

function checkpoint(overrides = {}) {
  const base = { checkpoint_version: 1, revision: 4, task: { id: "task-1", project: "project", goal: "goal", phase: "execute", status: "open" }, gates: { completed: ["intake"], open: ["execute", "verify"] }, workspace: { path: "/work", git_sha: "abc", branch: "main" }, constraints: { items: [], approval: { status: "not_required", request_refs: [] } }, evidence_refs: [{ id: "e1", kind: "test", locator: "evidence://1", digest: null }], receipt_refs: [{ id: "r1", kind: "receipt", locator: "receipt://1", digest: null }], handoff_refs: [{ id: "h1", kind: "handoff", locator: "handoff://1", digest: null }], semantic_progress: { semantic_state: "productive", last_productive_at: null, last_productive_cursor: 2, thinking_tokens_since_productive: 0 }, last_execution: { worker_id: "worker-a", native_session_id: "session-old", native_status: "interrupted" }, continuation: { next_action: { kind: "run_gate", gate_id: "execute", input_ref: null }, resume_cursor: "gate:execute", retry_count: 0, safe_to_resume: true } };
  return { ...base, ...overrides };
}
function plan(state = checkpoint()) { const termination = classifySessionTermination({ checkpoint: state, termination_evidence: { signals: ["interrupted"] } }); return planSameWorkerRespawn({ checkpoint: state, termination_result: termination, policy: { max_retry_count: 2 } }); }
function facts(overrides = {}) { const base = { workspace: { path: "/work", git_sha: "abc", branch: "main" }, human_block: "none", effect: { kind: "none", status: "none", prior_claim_keys: [] } }; return { ...base, ...overrides };
}
function preflight(state = checkpoint(), recoveryPlan = plan(state), runtimeFacts = facts()) { return evaluateResumePreflight({ checkpoint: state, plan: recoveryPlan, runtime_facts: runtimeFacts }); }

test("happy resume with matching workspace and no effect passes", () => { assert.deepEqual(preflight(), { decision: "pass", reason_code: "preflight_safe_to_execute", execution_allowed: true }); });
test("stale revision and task mismatch require replan", () => { const state = checkpoint(); assert.equal(preflight({ ...state, revision: 5 }, plan(state)).reason_code, "plan_checkpoint_revision_stale"); assert.equal(preflight(state, { ...plan(state), task_id: "other-task" }).reason_code, "plan_task_mismatch"); });
test("workspace path, SHA, and non-null branch mismatches require recovery", () => { for (const [field, value, reason] of [["path", "/other", "workspace_path_mismatch"], ["git_sha", "def", "workspace_git_sha_mismatch"], ["branch", "other", "workspace_branch_mismatch"]]) { const observed = facts({ workspace: { ...facts().workspace, [field]: value } }); assert.equal(preflight(checkpoint(), plan(), observed).reason_code, reason); } });
test("completed or no-longer-open next gate is never replayed", () => { const completed = checkpoint({ gates: { completed: ["intake", "execute"], open: ["verify"] } }); assert.equal(preflight(completed, plan()).decision, "already_completed"); const closed = checkpoint({ gates: { completed: ["intake"], open: ["verify"] } }); assert.equal(preflight(closed, plan()).reason_code, "next_gate_not_open"); });
test("approval, explicit human, and safety blocks refuse execution", () => { const base = checkpoint(); const pending = { ...base, constraints: { items: [], approval: { status: "pending", request_refs: ["approval:1"] } } }; assert.equal(preflight(pending, plan(base)).decision, "human_required"); for (const human_block of ["human_required", "safety_block"]) assert.equal(preflight(base, plan(base), facts({ human_block })).decision, "human_required"); });
test("unknown effect status or kind requires reconciliation", () => { for (const effect of [{ kind: "mutating", status: "unknown", prior_claim_keys: [] }, { kind: "unknown", status: "none", prior_claim_keys: [] }]) assert.equal(preflight(checkpoint(), plan(), facts({ effect })).decision, "recovery_required"); });
test("applied mutation and prior same claim prevent duplicate execution", () => { const respawn = plan(); assert.equal(preflight(checkpoint(), respawn, facts({ effect: { kind: "mutating", status: "applied", prior_claim_keys: [] } })).reason_code, "effect_already_applied"); assert.equal(preflight(checkpoint(), respawn, facts({ effect: { kind: "none", status: "none", prior_claim_keys: [respawn.claim_key] } })).reason_code, "claim_already_recorded"); });
test("known-not-applied mutation can proceed", () => { assert.equal(preflight(checkpoint(), plan(), facts({ effect: { kind: "mutating", status: "known_not_applied", prior_claim_keys: [] } })).execution_allowed, true); });
test("read-only replay proceeds only under explicit safe metadata", () => { assert.equal(preflight(checkpoint(), plan(), facts({ effect: { kind: "read_only", status: "applied", prior_claim_keys: [] } })).execution_allowed, true); assert.equal(preflight(checkpoint(), plan(), facts({ effect: { kind: "unknown", status: "applied", prior_claim_keys: [] } })).execution_allowed, false); });
test("preflight is deterministic, idempotent, and mutates neither input", () => { const state = checkpoint(); const recoveryPlan = plan(state); const runtimeFacts = facts(); const snapshots = [structuredClone(state), structuredClone(recoveryPlan), structuredClone(runtimeFacts)]; const first = preflight(state, recoveryPlan, runtimeFacts); assert.deepEqual(preflight(state, recoveryPlan, runtimeFacts), first); assert.deepEqual(state, snapshots[0]); assert.deepEqual(recoveryPlan, snapshots[1]); assert.deepEqual(runtimeFacts, snapshots[2]); });
test("completed-gate and required-reference drift fail closed", () => { const state = checkpoint(); const recoveryPlan = plan(state); assert.equal(preflight(state, { ...recoveryPlan, gates: { ...recoveryPlan.gates, completed: [] } }).reason_code, "completed_gates_drift"); const refsMissing = checkpoint({ evidence_refs: [] }); assert.equal(preflight(refsMissing, recoveryPlan).reason_code, "required_references_drift"); });
test("closed schemas reject prose and external orchestrator is absent", () => { assert.throws(() => preflight(checkpoint(), plan(), { ...facts(), prose: "safe" }), /unknown key/); const source = readFileSync(new URL("./resume-preflight.mjs", import.meta.url), "utf8"); assert.equal(source.includes(["Agent", "Navi"].join("")), false); });
