import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { classifySessionTermination } from "./session-termination.mjs";
import { acknowledgeSameWorkerRespawn, planSameWorkerRespawn } from "./same-worker-respawn.mjs";

function checkpoint(overrides = {}) {
  const base = { checkpoint_version: 1, revision: 4, task: { id: "task-1", project: "project", goal: "goal", phase: "execute", status: "open" }, gates: { completed: ["intake"], open: ["execute", "verify"] }, workspace: { path: "/work", git_sha: "abc", branch: "main" }, constraints: { items: [{ id: "bounded", status: "active", source_ref: "request:1" }], approval: { status: "not_required", request_refs: [] } }, evidence_refs: [{ id: "e1", kind: "test", locator: "evidence://1", digest: null }], receipt_refs: [{ id: "r1", kind: "receipt", locator: "receipt://1", digest: "sha256:1" }], handoff_refs: [{ id: "h1", kind: "handoff", locator: "handoff://1", digest: null }], semantic_progress: { semantic_state: "productive", last_productive_at: null, last_productive_cursor: 2, thinking_tokens_since_productive: 0 }, last_execution: { worker_id: "worker-a", native_session_id: "session-old", native_status: "interrupted" }, continuation: { next_action: { kind: "run_gate", gate_id: "execute", input_ref: "context://minimum" }, resume_cursor: "gate:execute", retry_count: 0, safe_to_resume: true } };
  return { ...base, ...overrides };
}
function result(signal, state = checkpoint()) { return classifySessionTermination({ checkpoint: state, termination_evidence: { signals: [signal] } }); }
function plan(signal, state = checkpoint(), max = 2) { return planSameWorkerRespawn({ checkpoint: state, termination_result: result(signal, state), policy: { max_retry_count: max } }); }

test("interrupted, timeout, and context exhaustion produce same-worker spawn plans", () => { for (const signal of ["interrupted", "session_timeout", "runtime_timeout", "context_exhausted"]) { const value = plan(signal); assert.equal(value.planned, true, signal); assert.equal(value.action, "spawn_same_worker"); assert.equal(value.source_worker_id, "worker-a"); assert.equal(value.target_native_session_id, null); } });
test("transient provider error and model stall candidates produce plans", () => { for (const signal of ["transient_provider_error", "model_stall"]) assert.equal(plan(signal).planned, true, signal); });
test("terminal, completed, cancelled, human, review, unknown, and continue outcomes produce no plan", () => {
  for (const status of ["completed", "cancelled"]) { const state = checkpoint({ task: { ...checkpoint().task, status } }); assert.equal(planSameWorkerRespawn({ checkpoint: state, termination_result: result("interrupted", state), policy: { max_retry_count: 2 } }).planned, false); }
  for (const signal of ["terminal_task_failure", "safety_block", "unknown", "normal_completion"]) assert.equal(plan(signal).planned, false, signal);
  const conflicting = classifySessionTermination({ checkpoint: checkpoint(), termination_evidence: { signals: ["interrupted", "model_stall"] } });
  assert.equal(planSameWorkerRespawn({ checkpoint: checkpoint(), termination_result: conflicting, policy: { max_retry_count: 2 } }).planned, false);
});
test("approval blocks respawn in depth", () => { const state = checkpoint({ constraints: { items: [], approval: { status: "pending", request_refs: ["approval:1"] } } }); const forgedEligible = { ...result("interrupted"), classification: "resumable", automatic_resume_eligible: true }; assert.equal(planSameWorkerRespawn({ checkpoint: state, termination_result: forgedEligible, policy: { max_retry_count: 2 } }).reason_code, "approval_blocks_respawn"); });
test("unsafe checkpoint, exhausted budget, or missing source identity produces no plan", () => {
  const unsafe = checkpoint({ continuation: { ...checkpoint().continuation, safe_to_resume: false } }); assert.equal(plan("interrupted", unsafe).reason_code, "checkpoint_not_safe_to_resume");
  const exhausted = checkpoint({ continuation: { ...checkpoint().continuation, retry_count: 2 } }); assert.equal(plan("session_timeout", exhausted, 2).reason_code, "retry_budget_exhausted");
  const noWorker = checkpoint({ last_execution: { worker_id: null, native_session_id: "session-old", native_status: "interrupted" } }); assert.equal(plan("interrupted", noWorker).reason_code, "source_worker_missing");
});
test("plan is deterministic, idempotent, immutable, and never targets the old session", () => { const state = checkpoint(); const before = structuredClone(state); const first = plan("interrupted", state); const second = plan("interrupted", state); assert.deepEqual(first, second); assert.deepEqual(state, before); assert.equal(first.target_native_session_id, null); assert.notEqual(first.target_native_session_id, first.source_native_session_id); assert.equal(Object.isFrozen(first), true); });
test("ack installs a new session and preserves durable task material", () => { const state = checkpoint(); const respawn = plan("context_exhausted", state); const updated = acknowledgeSameWorkerRespawn({ checkpoint: state, plan: respawn, new_native_session_id: "session-new" }); assert.equal(updated.revision, state.revision + 1); assert.equal(updated.continuation.retry_count, state.continuation.retry_count + 1); assert.deepEqual(updated.last_execution, { worker_id: "worker-a", native_session_id: "session-new", native_status: "running" }); for (const key of ["task", "gates", "evidence_refs", "receipt_refs", "handoff_refs"]) assert.deepEqual(updated[key], state[key], key); });
test("duplicate acknowledgement is idempotent and mismatches reject conservatively", () => { const state = checkpoint(); const respawn = plan("interrupted", state); const updated = acknowledgeSameWorkerRespawn({ checkpoint: state, plan: respawn, new_native_session_id: "session-new" }); assert.deepEqual(acknowledgeSameWorkerRespawn({ checkpoint: updated, plan: respawn, new_native_session_id: "session-new" }), updated); assert.throws(() => acknowledgeSameWorkerRespawn({ checkpoint: state, plan: respawn, new_native_session_id: "session-old" }), /must differ/); assert.throws(() => acknowledgeSameWorkerRespawn({ checkpoint: updated, plan: respawn, new_native_session_id: "session-other" }), /revision/); });
test("external orchestrator is not required", () => { const source = readFileSync(new URL("./same-worker-respawn.mjs", import.meta.url), "utf8"); assert.equal(source.includes(["Agent", "Navi"].join("")), false); });
