import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { restoreTaskCheckpoint, serializeTaskCheckpoint, updateTaskCheckpoint, validateTaskCheckpoint } from "./task-continuation.mjs";

function checkpoint(overrides = {}) {
  return { checkpoint_version: 1, revision: 3, task: { id: "task-123", project: "worker-neutral-supervisor", goal: "durable continuation", phase: "implementation", status: "open" }, gates: { completed: ["inspect"], open: ["test", "document"] }, workspace: { path: "/work/repo", git_sha: "abc123", branch: "main" }, constraints: { items: [{ id: "no-external-orchestrator", status: "active", source_ref: "request:constraint-1" }], approval: { status: "not_required", request_refs: [] } }, evidence_refs: [{ id: "e1", kind: "test", locator: "test://inspect", digest: null }], receipt_refs: [{ id: "r1", kind: "receipt", locator: "receipt://one", digest: "sha256:123" }], handoff_refs: [{ id: "h1", kind: "handoff", locator: "handoff://one", digest: null }], semantic_progress: { semantic_state: "productive", last_productive_at: null, last_productive_cursor: 4, thinking_tokens_since_productive: 0 }, last_execution: { worker_id: "worker-a", native_session_id: "session-old", native_status: "running" }, continuation: { next_action: { kind: "run_gate", gate_id: "test", input_ref: "ref://test-plan" }, resume_cursor: "gate:test", retry_count: 0, safe_to_resume: true }, ...overrides };
}
test("checkpoint validates and round-trips through one canonical representation", () => { const serialized = serializeTaskCheckpoint(checkpoint()); assert.deepEqual(restoreTaskCheckpoint(serialized), validateTaskCheckpoint(checkpoint())); assert.equal(serializeTaskCheckpoint(restoreTaskCheckpoint(serialized)), serialized); });
test("task identity is independent of replaceable native session identity", () => { const before = checkpoint(); const after = updateTaskCheckpoint(before, { last_execution: { worker_id: "worker-b", native_session_id: "session-new", native_status: "running" } }); assert.deepEqual(after.task, before.task); assert.equal(after.last_execution.native_session_id, "session-new"); });
test("replacing last session preserves completed gates and evidence references", () => { const before = checkpoint(); const after = updateTaskCheckpoint(before, { last_execution: { worker_id: "worker-a", native_session_id: "replacement", native_status: "interrupted" } }); assert.deepEqual(after.gates.completed, before.gates.completed); assert.deepEqual(after.evidence_refs, before.evidence_refs); assert.deepEqual(after.receipt_refs, before.receipt_refs); });
test("interrupted session reconstructs remaining gates and next action from latest checkpoint", () => { const latest = updateTaskCheckpoint(checkpoint(), { gates: { completed: ["inspect", "test"], open: ["document"] }, last_execution: { worker_id: "worker-a", native_session_id: "lost-session", native_status: "interrupted" }, continuation: { next_action: { kind: "run_gate", gate_id: "document", input_ref: null }, resume_cursor: "gate:document", retry_count: 0, safe_to_resume: true } }); const restored = restoreTaskCheckpoint(serializeTaskCheckpoint(latest)); assert.deepEqual(restored.gates.open, ["document"]); assert.deepEqual(restored.continuation.next_action, latest.continuation.next_action); assert.equal(restored.last_execution.native_status, "interrupted"); });
test("invalid or non-canonical state is rejected deterministically", () => { assert.throws(() => validateTaskCheckpoint(checkpoint({ gates: { completed: ["test"], open: ["test"] } })), /disjoint/); assert.throws(() => validateTaskCheckpoint({ ...checkpoint(), generated_at: new Date() }), /unknown key/); assert.throws(() => validateTaskCheckpoint(checkpoint({ semantic_progress: { ...checkpoint().semantic_progress, sampled_at_runtime: Date.now() } })), /unknown key/); const canonical = serializeTaskCheckpoint(checkpoint()); assert.throws(() => restoreTaskCheckpoint(JSON.stringify(JSON.parse(canonical))), /canonical/); });
test("external orchestrator is not required", () => { const source = readFileSync(new URL("./task-continuation.mjs", import.meta.url), "utf8"); const forbiddenName = ["Agent", "Navi"].join(""); assert.equal(source.includes(forbiddenName), false); });
